FROM node:16-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm i --ignore-scripts
COPY . .

FROM node:16-alpine

USER node
WORKDIR /app

COPY --from=build --chown=node:node  /app .
COPY --chown=node:node ./docker/api/entrypoint.sh .
RUN chmod +x ./entrypoint.sh
EXPOSE ${PORT}

ENTRYPOINT ["./entrypoint.sh"]
