version: "3"

services:
  redis:
    container_name: dev-redis-v-live
    image: redis:6.2.6-alpine
    restart: always
    command:
      - --loglevel warning
  db:
    container_name: dev-mysql-v-live
    image: mysql:5.7
    restart: always
    # platform: linux/x86_64 # for mac m1
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=dev@VLine22
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sequelize/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: none
    ports:
      - "0.0.0.0:33061:3306"
  app:
    container_name: dev-api-v-live
    image: dev-be-v-live
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "4500:${PORT}"
    command: sh ./entrypoint.sh
    env_file:
      - .env
    volumes:
      - .:/app
      - ignore:/app/node_modules/
    depends_on:
      - "db"
volumes:
  ignore:
