export {default as auth} from './auth';
export {default as user} from './user';
export {default as admin} from './admin';
export {default as wallet} from './wallet';
export {default as supplier} from './suppliers/supplier.route';
export {default as storesSuppliers} from './suppliers/stores.suppliers.route';
export {default as rolesSuppliers} from './suppliers/roles.suppliers.route';
export {default as messages} from './messages/messages.route';
export {default as channels} from './channels/channels.route';
export {default as usersChannels} from './userschannels/userschannels.route';
export {default as stripe} from './stripe';
export {default as address} from './address/address';
export {default as policy} from './policies/policy';
export {default as bloodType} from './bloodTypes/bloodType';
export {default as specificBank} from './specificBanks/specificBank';
export {default as genderTypes} from './genderTypes/genderTypes.route';
export {default as protectors} from './protectors/protectors.route';

export {default as currency} from './currency';
