name: Deploy staging

on:
  push:
    branches: [ "stg" ]
  pull_request:
    branches: [ "stg" ]

jobs:

  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Deploy V-live
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        username: ${{ secrets.SERVER_SSH_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: cd /var/opt/v-line-backend/ && git pull origin stg && docker-compose -f docker-compose-stg.yml up -d --build app && echo y | docker system prune -a
